import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
    title: "Terms of Service — LyFeOS",
    description: "Terms and conditions for using LyFeOS.",
};

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-mindful-gradient">
            <div className="fixed inset-0 bg-warm-glow opacity-40 pointer-events-none" />
            <div className="relative z-10 max-w-2xl mx-auto px-6 py-16 pb-32">
                <Link
                    href="/login"
                    className="inline-flex items-center gap-2 text-xs text-amber-200/40 hover:text-amber-200/70 transition-colors mb-10"
                >
                    <ArrowLeft className="w-3 h-3" />
                    Back
                </Link>

                <h1 className="text-3xl font-light text-amber-100 mb-2 tracking-wide">Terms of Service</h1>
                <p className="text-xs text-amber-200/30 mb-10">Last updated: February 21, 2025</p>

                <div className="space-y-8 text-sm text-amber-200/70 leading-relaxed font-light">
                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Acceptance</h2>
                        <p>By creating an account on LyFeOS, you agree to these terms. If you do not agree, please do not use the service.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">The Service</h2>
                        <p>LyFeOS is a personal life-intelligence platform. You use it to log daily reflections, set weekly intentions, and receive AI-generated behavioral insights. The platform is designed for personal use only.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Your Data</h2>
                        <p>You own your data. LyFeOS does not claim any ownership over the content you create. You may export or delete your data at any time.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">AI-Generated Insights</h2>
                        <p>Weekly intelligence reports are generated by artificial intelligence (Google Gemini). These insights are analytical observations based on your self-reported data — they are not professional medical, psychological, or financial advice. LyFeOS is not a substitute for professional care.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Account Security</h2>
                        <p>You are responsible for maintaining the security of your account credentials. LyFeOS is not liable for unauthorized access resulting from compromised passwords.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Account Deletion</h2>
                        <p>You may permanently delete your account and all associated data at any time from the Settings panel. This action is immediate and irreversible. LyFeOS maintains a zero-retention policy — once deleted, your data cannot be recovered.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Acceptable Use</h2>
                        <p>You agree not to use LyFeOS for any unlawful purpose, to attempt to access other users&apos; data, or to reverse-engineer the platform. One account per person.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Limitation of Liability</h2>
                        <p>LyFeOS is provided &quot;as is.&quot; We make no warranties about the accuracy of AI-generated insights. In no event shall LyFeOS be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Changes</h2>
                        <p>We may update these terms periodically. Continued use of LyFeOS after changes constitutes acceptance of the updated terms.</p>
                    </section>

                    <section>
                        <h2 className="text-xs uppercase tracking-widest text-amber-400/60 font-semibold mb-3">Contact</h2>
                        <p>Questions? Reach us at <span className="text-amber-300/80">connect@lyfeos.in</span></p>
                    </section>
                </div>
            </div>
        </main>
    );
}
